### ISSUE TITLE
Code-Generierung mit JAXB: Fehler in Schema, LearningOutcomeType

### ISSUE THREAD

**Issue by MichaelLierath** [OZG-TFBildung/XBildung#1]
Autor: Michael Lierath
Art der Organisation: HIS eG, CAMS-Hersteller

Bei der Code-Generierung von Java-Klassen mithilfe von JAXB tritt folgender Fehler auf:

> Komplexer Typ und sein untergeordnetes Element verwenden denselben Namen "LearningOutcomeType". Lösen Sie diesen Konflikt mit einer Klassenanpassung.
> com.sun.istack.SAXParseException2; systemId: http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd; lineNumber: 6798; columnNumber: 21; Komplexer Typ und sein untergeordnetes Element verwenden denselben Namen "LearningOutcomeT ype". Lösen Sie diesen Konflikt mit einer Klassenanpassung.

Die Dopplung der von Typ und Element befindet sich im folgenden Schema, Zeile 6798:
http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd

Workaround mithilfe einer bindings-Datei für das Schema:

```
<bindings node="//xs:complexType[@name='LearningOutcomeType']">
    <class name="LearningOutcomeTypeEl"/>
</bindings>
```

**Comment by init-xbildung** [comment]
in XBildung V0.9 haben wir den direkten Import des EDCI-Schemas ausgebaut. Ein XBildungs-Bildungsnachweis erbt nicht länger von einem EDCI credential. Hintergründe für den Ausbau führen wir im kommenden ersten XHochschule-Newsletter aus:
(URL coming soon)
Aus unserer Sicht kann das Ticket damit geschlossen werden.
