### ISSUE TITLE
Verortung des Vorbereitungsdienstes

### ISSUE THREAD

**Issue by lummerland** [OZG-TFBildung/XBildung#13]
Autor: Manuel Kummerländer
Art der Organisation: andere
Beschreibung:

Hallo zusammen,

wir etablieren und pflegen in unserem Projekt unter anderem Vokabulare zu Bildungsstufen, Abschlüssen etc. im Schul- und Hochschulbereich. Aktuell versuchen wir, den Vorbereitungsdienst bzw. das zweite Staastsexamen einzubringen und zu verorten. Dafür schauen wir uns auch nach Beispielen um. XBildung setzt wohl stark auf die Systematiken der destatis und KMK, dort ist der Vorbereitungsdienst m.E. so explizit nicht zu finden. 
Bilden Sie den Vorbereitungsdienst derzeit anderweitig/implizit mit ab oder ist geplant, das in Zukunft zu tun?

Vielen Dank im Voraus.
Viele Grüße
Manuel

**Comment by init-xhochschule** [comment]
Lieber Herr Kummerländer,

gern nehmen wir Hinweise auf andere Vorhaben auf und prüfen andere Vokabulare zu Bildungsstufen, Abschlüssen etc. im Schul- und Hochschulbereich. Das Nachveröffentlichen von KMK und DESTATIS Vokabularen in maschinenverarbeitbarer Form ist eher als Workaround zu sehen, bis dies auch an der Quelle der Vokabulare möglich ist. Können Sie uns bitte einen Link oder weitere Informationen zu Ihrem Vorhaben geben?

Zu Ihrer Frage: Der Vorbereitungsdienst ist als Leika-Leistungen referenziert und ist in den Beschreibungen des Standardisierungsbedarfes aufgeführt: https://xhochschule.de/def/req/1.0/Bedarfsbeschreibung_XHochschule.pdf (https://xhochschule.de/def/req/1.0/Bedarfsbeschreibung_XHochschule.pdf

In XHochschule oder XSchule steht die Unterstützung dieses Themas aktuell nicht im Scope (hier sind nach unserer Kenntnis auch eher die Länder involviert, nicht die Hochschulen). 

Viele Grüße
Martin Herzog

**Comment by lummerland** [comment]
Hallo Herr Herzog,

vielen Dank für die hilfreiche Rückmeldung. 
In unserem Projekt (wirlernenonline.de) sind wir regelmäßig dabei unsere Metadatenstrukturen zu verbessern oder an neue Realitäten anzupassen. Dabei fiel uns zuletzt eben auf, dass der Vorbereitungsdienst bei uns noch nicht verortet ist. Daher wollten wir uns informieren, wie dazu der aktuelle Stand in anderen Standards und Datenprofilen aussieht um ggf. daran anzuknüpfen.
Ich schließe das Ticket ab, denn meine Frage haben Sie ja beantwortet.

Beste Grüße
Manuel Kummerländer
