### ISSUE TITLE
Code-Generierung mit JAXB: Fehler in Schema, AccreditationType

### ISSUE THREAD

**Issue by MichaelLierath** [OZG-TFBildung/XBildung#2]
Autor: Michael Lierath
Art der Organisation: HIS eG, CAMS-Hersteller

Bei der Code-Generierung von Java-Klassen mithilfe von JAXB tritt folgender Fehler auf:

> Zwei Deklarationen verursachen eine Kollision in der ObjectFactory-Klasse.
> com.sun.istack.SAXParseException2; systemId: http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd; lineNu
> mber: 4567; columnNumber: 47; Zwei Deklarationen verursachen eine Kollision in der ObjectFactory-Klasse.

Die Dopplung der Namen befindet sich im folgenden Schema, Zeilen 4567 und 5525:
http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd

Workaround mithilfe einer bindings-Datei für das Schema:

```
<bindings node="//xs:complexType[@name='AccreditationType']">
    <class name="AccreditationTypeEl"/>
</bindings>
```

Der Fehler scheint in einer aktuelleren Version von EDCI (1.0 bzw. 1.1) behoben zu sein.

**Comment by init-xbildung** [comment]
Wir schließen dieses Ticket mit Verweis auf die Antwort zum ähnlichen Ticket  
https://github.com/OZG-TFBildung/XBildung/issues/1#issuecomment-1068072414
