### ISSUE TITLE
Code-Generierung mit JAXB: Fehler in Schema, TargetFrameworkName

### ISSUE THREAD

**Issue by MichaelLierath** [OZG-TFBildung/XBildung#3]
Autor: Michael Lierath
Art der Organisation: HIS eG, CAMS-Hersteller

Bei der Code-Generierung von Java-Klassen mithilfe von JAXB tritt folgender Fehler auf:

> Eigenschaft "TargetFrameworkName" ist bereits definiert. Verwenden Sie &lt;jaxb:property> zur Lösung dieses Konflikts.
> com.sun.istack.SAXParseException2; systemId: http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd; lineNumber: 4472; columnNumber: 126; Eigenschaft "TargetFrameworkName" ist bereits definiert. Verwenden Sie &lt;jaxb:property>
>  zur Lösung dieses Konflikts.

Die Dopplung der Attribute befindet sich im folgenden Schema, Zeilen 4472 und 4484:
http://xbildung.de/def/edci/0.10.0.edited/flatten/genericschema.xsd

Workaround mithilfe einer bindings-Datei für das Schema:

```
<bindings node="//xs:complexType[@name='CredentialTypeType']">
        <bindings node=".//xs:attribute[@name='targetFrameworkName']">
            <property name="TargetFrameworkName2"/>
        </bindings>
</bindings>
```

**Comment by init-xbildung** [comment]
Wir schließen dieses Ticket mit Verweis auf die Antwort zum ähnlichen Ticket
https://github.com/OZG-TFBildung/XBildung/issues/1#issuecomment-1068072414
