### ISSUE TITLE
I18n der Codelisten

### ISSUE THREAD

**Issue by ArnWassmann** [OZG-TFBildung/XBildung#5]
Autor: Arn Waßmann | HIS eG
Art der Organisation: CaMS-Hersteller
Beschreibung: 

Guten Tag,

für unsere Planungen wäre spannend zu wissen ob und wann mit (offiziellen) übersetzen Einträgen in den Code-Listen, wie bspw. urn-xbildung-de-xbildung-codeliste-artderhzb_0.8.xml, zu rechnen ist.

Vielen Dank und beste Grüße
Arn Waßmann

**Comment by ThemenfeldBildung** [comment]
Guten Tag,

derzeit gibt es noch keine genaueren Planungen, ob und ab wann wir offizielle Übersetzungen bereitstellen werden. Allerdings sieht die Roadmap vor, dass wir uns Mitte des Jahres mit den Anforderungen beschäftigen, die aus dem Bereich SDG kommen. Wir gehen davon aus, dass wir in diesem Kontext auch die Mehrsprachigkeit von Codelisten betrachten müssen.

Viele Grüße
Ludger Rinsche

**Comment by init-xbildung** [comment]
Eine Übersetzung der "nationalen" deutschsprachigen Bezeichnungen der "Arten der HZB" sind von Seiten XBildung aktuell nicht in Planung. 
Wir werden aber die Häufigkeit des Feldes im Abiturzeugnis bis zu einem XSchule V0.3 überprüfen und auch nach Ihren Hinweisen @ArnWassmann (https://github.com/OZG-TFBildung/XHochschule/issues/14)  auch die Einträge der Liste an sich für ein XBildung 1.0.

Übersetzungsaktivitäten der EU-KOM in dieser Richtung im Rahmen von SDG sind aktuell nicht bekannt, wir haben da aber "das Ohr auf der Schiene". Mehrsprachige Thesauri teilweise in allen EU-Sprachen sind regelmäßig hier vom Publications Office angeboten: https://op.europa.eu/en/web/eu-vocabularies/controlled-vocabularies

Für EU-Interoperabilität von Aussagen zu Wertigkeiten, Äquivalenzen von deutschen Bildungsabschlüssen der secondary education auf EU-Ebene sind bei Abiturzeugnissen in XSchule Angaben zum DQR möglich und zukünftig gemappt auf den entsprechenden EQR-Schlüssel.
Wir orientieren uns hierbei an Informationen hier: https://www.dqr.de/dqr/de/der-dqr/dqr-und-eqr/dqr-und-eqr_node.html;

![image](https://user-images.githubusercontent.com/99474274/158407843-5c6a5d0b-65a5-4629-b3b7-8672066080e7.png)

Viele Grüße, Sebastian Sklarß
