### ISSUE TITLE
Anforderungen an Geokoordinaten in Adressen

### ISSUE THREAD

**Issue by AlexanderSotek** [OZG-TFBildung/XBildung#6]
Autor:  Alexander Sotek | HIS eG
Art der Organisation: CaMS-Hersteller
Beschreibung:
In der Dokumentation zur _Meldeanschrift_ (xsd/xbildung-baukasten.xsd) heißt es:

_Die Anschrift kann außerdem über eine Subkomponente verfügen, die eine Beschreibung des Ortes
mittels Geokoordinaten erlaubt._

Gibt es bereits Vorgaben oder konkrete Vorschläge, wie diese Beschreibung umgesetzt werden sollte? 

Vielen Dank und Viele Grüße
Alexander Sotek

**Comment by ArnWassmann** [comment]
Autor: Arn Waßmann | HIS eG
Art der Organisation: CaMS-Hersteller
Beschreibung:

Hallo,

für unsere Planungen, wann ist hier in etwas mit einer Klärung zu rechnen?

Vielen Dank und beste Grüße
Arn Waßmann

**Comment by init-xbildung** [comment]
Guten Tag,

vielen Dank für diesen Hinweis. Bei der zitierten Textstelle handelt es sich um einen redaktionellen Fehler bei der Übernahme der Meldeanschrift.

Es ist uns derzeit kein Use-Case bekannt, in dem eine Beschreibung des Ortes per Geo-Koordinaten relevant wäre. Wir werden den Hinweis (ebenso wie den Hinweis auf die verwaltungspolitische Kodierung) in der nächsten Version aus der Beschreibung entfernen.

Mit freundlichen Grüßen
Ludger Rinsche

**Comment by init-xbildung** [comment]
Wir haben in XBildung V0.9 den Hinweis berücksichtigt und optionale Möglichkeiten zur Angabe von Geokodierung für Bildungseinrichtungen (die z.B. Schulzeugnisse ausstellen) entfernt.
Angaben zur verwaltungspolitschen Kodierung (Kreis, Land, Bundesland, Staat) einer einen Bildungsnachweis ausstellenden Bildungseinrichtung sind weiterhin möglich und dienen dazu z.B. den Kreis- oder Gemeindeschlüssel einer ausstellenden Schule zu hinterlegen.


Beispielhaft: 
AGS 05774032 von Lemgo in https://xschule.digital/def/xschule/0.2/xml/XSchule_Abiturzeugnis_NW_01.xml

![image](https://user-images.githubusercontent.com/99474274/158402389-5aecb5a3-200f-4d30-af00-22b75c6ab6fd.png)
