### ISSUE TITLE
Fehlender Bezug zu Staat in xbd:Meldeanschrift und damit in xbd:Geburt für Geburt im Ausland

### ISSUE THREAD

**Issue by mserve** [OZG-TFBildung/XBildung#7]
Nach https://github.com/OZG-TFBildung/XBildung/blob/de47fa0347989e10bc71ed4aeed813875066cdd1/xsd/xbildung-baukasten.xsd#L1204 ist der Geburtsort einer Person eine **xbd:Meldeanschrift**. Diese enthält aber keine Information zum Staat in dem sich diese Anschrift befindet. Demnach lässt sich in 

https://github.com/OZG-TFBildung/XBildung/blob/de47fa0347989e10bc71ed4aeed813875066cdd1/xsd/xbildung-baukasten.xsd#L1206

entgegen der Angabe kein Geburtsort mit vermerktem Staat abbilden, demnach wären in XBildung und allen darauf aufbauenden Standards wie XSchule nur deutsche Geburtsorte abbildbar, oder?

**Comment by init-xbildung** [comment]
Vielen Dank für den Hinweis @mserve den wir in XBildung V0.9 wie folgt berücksichtigt haben:
Der Geburtsort bindet nun nicht mehr die `XMeld:Meldeanschrift`  ein sondern die allgemeinere XÖV-Kernkomponente `Anschrift.` Hier sind nun Angaben zum Staat möglich und Plausibilitäten auf der Postleitzahl entfernt. 
Damit ist es nun möglich auch Geburtsorte außerhalb des Einzugsbereiches von Melderegistern in Deutschland abzubilden.


![image](https://user-images.githubusercontent.com/99474274/158411443-1bbed27f-071f-410f-bbb3-071b610e70f8.png)


Viele Grüße, 
Sebastian Sklarß
