### ISSUE TITLE
XBildung-Baukasten referenziert www.w3.org als http

### ISSUE THREAD

**Issue by MichaelLierath** [OZG-TFBildung/XBildung#8]
Hallo, 

wir generieren Java-Code aus dem XSD-Schema mithilfe von des Maven-Plugins cxf-xjc-plugin. Heute trat dabei dieser Fehler auf: 

----
[DEBUG] MSG: http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd
[DEBUG] Severity: 2
[DEBUG] Line: 1
[DEBUG] Col: 1
[DEBUG] Vorzeitiges Dateiende.
[DEBUG] org.xml.sax.SAXParseException; systemId: http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema
.xsd; lineNumber: 1; columnNumber: 1; Vorzeitiges Dateiende.
[DEBUG] 	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWra
pper.java:204)
----

Der Fehler ist zurückzuführen auf ein aktuelles Eperiment der w3c-Webseite: [https://www.w3.org/blog/2022/07/redirecting-to-https-on-www-w3-org/](url)

Auch wenn der aktuelle Zustand (Weiterleitung mit 307) temporär ist, sollte die Schema-Location der w3c-Schemata vorsorglich auf https geändert werden. 

Viele Grüße
Michael Lierath

**Comment by init-xbildung** [comment]
Guten Tag,

die Verwendung der http-URI ist bereits ein Workaround, da eins der Werkzeugt die https-Version nicht verarbeiten konnte. Wir hoffen aber, dass dieser Bug in späteren Version behoben wird.

Bis dahin werden wir, beginnend mit der kommenden Version von XBildung, die XSD manuell anpassen.

Mit freundlichen Grüßen
Ludger Rinsche
